import './globals.css'
import { Open_Sans, Inter } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
const inter = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Lamamia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <Navbar />

          {children}
          
          <Footer />
        </div>
      </body>
    </html>
  )
}
